# Generated by Django 3.2 on 2021-05-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('index1', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('logo_URL', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('members', models.TextField(blank=True)),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
            ],
        ),
    ]
