# Generated by Django 3.2 on 2021-04-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('teamOne', models.CharField(max_length=100)),
                ('teamTwo', models.CharField(max_length=100)),
                ('teamOne_count', models.IntegerField(default=0)),
                ('teamTwo_count', models.IntegerField(default=0)),
            ],
        ),
    ]
