# Generated by Django 3.2 on 2021-04-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_teambets_teambet'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambet',
            name='description',
            field=models.TextField(default='Hell'),
        ),
    ]
