# Generated by Django 3.2 on 2021-05-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_teambet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambet',
            name='datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
