# Generated by Django 3.2 on 2021-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_teambet_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teambet',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
