# Generated by Django 3.2 on 2021-05-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_teambet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambet',
            name='datetime',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teambet',
            name='description',
            field=models.TextField(default='Hell'),
        ),
    ]
