# Generated by Django 3.2 on 2021-05-01 16:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamBet',
            new_name='Bet',
        ),
        migrations.RenameModel(
            old_name='Points',
            new_name='Point',
        ),
    ]
