# Generated by Django 3.2 on 2021-05-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_point_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='datetime',
        ),
    ]
