# Generated by Django 3.2 on 2021-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_point_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='teamOne_users',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='teamTwo_users',
            field=models.TextField(blank=True),
        ),
    ]
