# Generated by Django 3.2 on 2021-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210503_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
