# Generated by Django 3.2 on 2021-05-03 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_bet_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='image_URL',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
