# Generated by Django 3.2 on 2021-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_bet_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='winner',
            field=models.CharField(blank=True, choices=[(models.CharField(max_length=100), models.CharField(max_length=100)), (models.CharField(max_length=100), models.CharField(max_length=100))], max_length=100),
        ),
    ]
