# Generated by Django 3.2 on 2021-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_bet_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='winner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
