# Generated by Django 3.2 on 2021-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_bet_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='teamOne_users',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='teamTwo_users',
        ),
        migrations.AddField(
            model_name='bet',
            name='betLog',
            field=models.TextField(blank=True),
        ),
    ]
