# Generated by Django 3.2 on 2021-05-05 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20210504_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='pointLog',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
