# Generated by Django 3.2 on 2021-05-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_auto_20210505_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='video_URL',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
