# Generated by Django 3.2 on 2021-05-15 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('books', '0021_bet_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetEntrie',
            fields=[
                ('bet_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('concerned', models.CharField(max_length=300)),
                ('amount', models.IntegerField(default=0)),
                ('entry', models.CharField(blank=True, max_length=300)),
                ('bet_odds', models.FloatField(default=1.0)),
                ('betted', models.BooleanField(default=False)),
                ('rewarded', models.BooleanField(default=False)),
                ('user_entered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_entry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_one', models.CharField(max_length=300)),
                ('bet_one_option_one', models.CharField(max_length=100)),
                ('bet_one_option_one_odds', models.FloatField(default=1.0)),
                ('bet_one_option_two', models.CharField(max_length=100)),
                ('bet_one_option_two_odds', models.FloatField(default=1.0)),
                ('bet_one_winner', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('image_URL', models.CharField(max_length=200)),
                ('video_URL', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Rewarded', 'Rewarded')], default='Upcoming', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('teamOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_One', to='teams.team')),
                ('teamTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_Two', to='teams.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.AddField(
            model_name='point',
            name='xp_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='point',
            name='xp_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='points',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='betoption',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_for_match', to='books.match'),
        ),
    ]
